2022-03-18 18:04:36,434 ERROR: Exception on /user/test [GET] [in C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\junting.ma\Documents\Documents\GitHub\practice\flask\app\routes.py", line 106, in user
    return render_template('user.html', title = 'Profile', user = user,
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\jinja2\environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\junting.ma\Documents\Documents\GitHub\practice\flask\app\templates\user.html", line 38, in <module>
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2022-03-18 18:04:44,463 ERROR: Exception on /user/test [GET] [in C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\junting.ma\Documents\Documents\GitHub\practice\flask\app\routes.py", line 106, in user
    return render_template('user.html', title = 'Profile', user = user,
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\jinja2\environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\junting.ma\Documents\Documents\GitHub\practice\flask\app\templates\user.html", line 38, in <module>
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2022-03-18 18:04:51,061 ERROR: Exception on /user/test2 [GET] [in C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\junting.ma\Documents\Documents\GitHub\practice\flask\app\routes.py", line 106, in user
    return render_template('user.html', title = 'Profile', user = user,
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\jinja2\environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\junting.ma\Documents\Documents\Anaconda\envs\flask\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\junting.ma\Documents\Documents\GitHub\practice\flask\app\templates\user.html", line 38, in <module>
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2022-03-18 18:05:32,468 INFO: Hello [in C:\Users\junting.ma\Documents\Documents\GitHub\practice\flask\app\__init__.py:33]
2022-03-18 18:07:08,338 INFO: Hello [in C:\Users\junting.ma\Documents\Documents\GitHub\practice\flask\app\__init__.py:33]
2022-03-21 11:51:10,806 INFO: Hello [in C:\Users\junting.ma\Documents\Documents\GitHub\practice\flask\app\__init__.py:33]
2022-03-21 11:52:23,119 INFO: Hello [in C:\Users\junting.ma\Documents\Documents\GitHub\practice\flask\app\__init__.py:33]
2022-03-21 11:52:58,841 INFO: Hello [in C:\Users\junting.ma\Documents\Documents\GitHub\practice\flask\app\__init__.py:33]
2022-03-22 10:54:51,778 INFO: Hello [in C:\Users\junting.ma\Documents\Documents\GitHub\practice\flask\app\__init__.py:33]
2022-03-22 10:55:04,592 INFO: Hello [in C:\Users\junting.ma\Documents\Documents\GitHub\practice\flask\app\__init__.py:33]
